# PORTFOLIO - Andrew Phakeovilay

Bienvenue dans le portfolio de Andrew Phakeovilay où vous trouverez ses projets.

=== À propos de moi

> Étudiant en informatique. Motivé pour développer mes compétences informatiques telles que Java (8,17), Python 3, SQL, C, HTML5 & CSS3, Asciidoc, PHP, JavaScript, TypeScript, mySQL en langages de programmation.
> Je suis capable de manipuler des logiciels tels qu'Eclipse, EduPython, Spyder,  SQLdeveloper, Repl.it, PlantUML, SceneBuilder, Visual Studio Code, VirtualBox, WinDesign, Angular, MobaxTerm.
> Pour gérer et travaille en projet, j'utilise GitHub et ProjectLibre pour créer les planifications de projets et des diagrammes de Gantt.

== Au sein de l'IUT

* J'ai développé une application de capteurs et un site E-commerce d'un client sous méthode SCRUM (GitHub, Java, Python, sqlDeveloper, MobaXterm, Eclipse, IntelliJ, PyCharm) 
+
_Travailler en équipe, gérer les conflits, rédiger des documentations, réunion méthode SCRUM avec le client_

* J'ai travaillé en tant que chef de groupe sur le développement d'une application banque sur Java en lien avec une base de données, donc je fais preuve d'autonomie, d'organisation et de gestion de conflit. (GitHub, Java 8, JavaFX, IDE Eclipse)
+
_Travailler en équipe en tant que chef de projet, savoir gérer les conflits_

* J'ai géré une base de données d'une entreprise où j'ai eu à améliorer l'existant et documenter
+
_Étudier une base de données existante et l'améliorer_

* J'ai crée des applications Java tels que la recherche d'étudiant d'un département informatique, le BlackJack avec JavaFX
+
_Apprendre du JavaFX et créer une interface homme machine_
* J'ai appris à créer une machine virtuelle Ubuntu avec les fonctionnalités principales (des logiciels, personnation du terminal)
+
_Installation de logiciels, personnalisation, création des utilisateurs, des groupes, script shell_

* J'ai crée un site ergonomique d'entreprises GREEN IT sous HTML5 & CSS3 sur Visual Studio Code
_Collecte de données pertinentes, optimisation du code HTML & CSS_

* J'ai crée une application permettant d'obtenir les étudiants d'un département informatique avec des contraintes
(Java 17, IDE BlueJ)
_Développement des fonctions optimisées en respectant les contraintes comme tirer tous les étudiants au moins une fois_

* J'ai crée le jeu du pendu sous Python avec une interface utilisateur
+
_Pratique des notions python et création d'une interface_
== Au sein d'une entreprise

* J'ai effectué mon stage du semestre 4 en 2ème année BUT Informatique chez Mecaprotec sur la migration d'un serveur LAMP
+
_Migration d'un serveur existant afin d'optimiser la production, communication interpersonnelle, travail d'équipe, maîtrise des applications d'entreprises_
* J'ai également travaillé en tant qu'opérateur de production en intérim chez Continental en job d'été.
+
_Assemblage de pièces et maintenance des machines, être automne et savoir travailler en
équipe_

En termes de centres d'intérêt, j'aime la simulation, effectuer des tests, j'aime aussi le design, l'esthétique des interfaces et j'aime la technologie auquel je me tiens au courant tous les jours.

Je suis actuellement en recherche d'alternance en tant que développeur informatique pour ma 3ème BUT Informatique. En profil professionnel, je voudrais devenir développeur d'applications après un Master.

== Contact

Je vous laisse mes contacts afin que vous pouvez me contacter

* Email : andrew.p_pro@outlook.com
* N° Téléphone : 07 69 34 50 43
* Linkedin : https://www.linkedin.com/in/andrew-phakeovilay-731925234/
