= Documentation technique
:numbered:

== Elle devait contenir :

- Page de garde ✅
- Sommaire ✅
- Présentation de l'Application  ✅
- Répartition des fonctionnalités par programmeur (Une section qui décrit le partage du travail)
- Expliquer le diagramme de classe des données global (base de données), surtout les éléments particuliers (par exemple chef Agence, client inactif, …) qui servent et concernent le code développé.
- Architecture de l’application  ✅
- Comment installer l’appli, la base pour un projet eclipse
- Comment lancer le jar

=== Architecture
        
- Architecture générale (poste client, serveurs, …) et rôle de chaque élément  ✅
- Ressources externes (.jar, …) utilisées et rôles ✅
- Structuration en packages de l’application documentée. Principes retenus pour cette structuration  ✅
- Eléments essentiels à connaître, spécificités, … nécessaires à la mise en œuvre du développement. Cette partie peut être illustrée par un diagramme de séquence

=== Fonctionnalités

Pour chaque fonctionnalité : en les expliquant
Dans chaque partie : qui est le développeur responsable    

- Partie de use case réalisé - scénarios éventuels
- Partie du diagramme de classes données nécessaires : en lecture, en mise à jour
- Copies écrans principales de la fonctionnalité (ou renvoi vers doc utilisateur) + maquettes états imprimés (si concerné)
- Classes impliquées dans chaque package
- Extraits de code significatifs commentés si nécessaires pour des points particuliers et importants avec spéc. ddées
- Eléments essentiels à connaître, spécificités, … nécessaires à la mise en œuvre du développement. Cette partie peut être illustrée par un diagramme de séquence

== Evaluation

Points d'amélioration :

- Manque certains éléments dans la doc (cf. section précédente)
- Comment on installe ?
- Comment on lance le jar ?
- README trop minimaliste

Points positifs :

- Bonne doc technique (mais incomplète) !


